name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Debug SSH Key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 5

    - name: Build the project
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.80.203.92 << 'EOF'
        cd /var/www/banhcuon/html
        git fetch --all
        git reset --hard origin/main  # Force reset to the latest commit on main
        git pull origin main
        npm install
        npm run build
        sudo systemctl restart nginx
        EOF
